import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/context/theme.context";
import { Footer, Header } from "./components";
import SidebarProvider from "@/context/sidebar.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Go Stock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <SidebarProvider>
            <Header />
            {children}
            <Footer />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
